services:
  minio:
    container_name: minio
    image: minio/minio:latest

    command: ['server', '/data', '--console-address', ':9001']
    ports:
    - "9000:9000" # api
    - "9001:9001" # gui

    environment:
    - "MINIO_ROOT_USER=admin"
    - "MINIO_ROOT_PASSWORD=password"

    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 1s
      timeout: 20s
      retries: 20

  mc:
    image: minio/mc:latest
    container_name: mc_test
    depends_on:
      minio:
        condition: service_healthy
    environment:
    - "MINIO_ROOT_USER=admin"
    - "MINIO_ROOT_PASSWORD=password"
    entrypoint: >
      /bin/sh -c "
        mc alias set minio http://minio:9000 admin password && 
        mc mb minio/my-bucket || true && 
        mc cp --recursive /init_data/ minio/my-bucket
        mc anonymous set public minio/my-bucket; exit 0;
      "
    volumes:
        - ./testdata:/init_data
